### ISSUE TITLE
关于Secret的问题我可能没有表述清楚

### ISSUE THREAD

**Issue by ixmu** [ellermister/mtproxy#10]
下面截图中圈起来的部分应该是一致的才对吧？
如果不用链接，我按照提示的ip、端口、secret输入是无法连接的

![QQ截图20201215175145.png](https://i.loli.net/2020/12/15/vnKXkgbuFYiyNhs.png)

**Comment by ellermister** [comment]
已经改好了。

**Comment by ixmu** [comment]
> 已经改好了。

mtproxy secrt可以自己设置吗？
我在mtp_config里面设置，是无效的

**Comment by ellermister** [comment]
> > 已经改好了。
> 
> mtproxy secrt可以自己设置吗？
> 我在mtp_config里面设置，是无效的
> 还是说使用tls，一定会加上域名的编码？

使用TLS连接时，客户端的secret是经过编码的：`ee${secret}${domain_hex}`
