### ISSUE TITLE
希望脚本支持监听地址设置

### ISSUE THREAD

**Issue by cncherisher** [ellermister/mtproxy#11]
用的是nginx的stream模块来反代,mtproxy本身的端口不需要开放到公网

**Comment by jerrell851** [comment]
这个提议好，希望作者加入，更安全，还可以复用443端口。

**Comment by haomuch** [comment]
这样是否可以实现和v2ray共用服务端443端口？

**Comment by LovelyHaochi** [comment]
@haomuch 可以试试nginx路径分流

**Comment by ellermister** [comment]
通过 Docker 已经集成Nginx，并支持白名单。
