### ISSUE TITLE
TMProxy+TLS代理: 已停止

### ISSUE THREAD

**Issue by PineappleBeer** [ellermister/mtproxy#15]
你好，请问openvz是无法使用这个脚本的吗？

**Comment by ellermister** [comment]
opennvz 支持不好，需要具体看报错情况。
 `bash mtproxy debug`

**Comment by yxbinghe-k** [comment]
遇到了同样的问题！
之前一切正常！
今天重启服务后，就不能正常启动了！

**Comment by ellermister** [comment]
删除镜像重新安装
@yxbinghe-k  @PineappleBeer

**Comment by yxbinghe-k** [comment]
> 删除镜像重新安装 @yxbinghe-k @PineappleBeer

只能在docker下跑么？
一键部署，不更新支持了么！？😊
