### ISSUE TITLE
Docker镜像php7.4环境如何开启GD库？

### ISSUE THREAD

**Issue by shipinbaoku** [ellermister/mtproxy#19]
Docker镜像php7.4环境如何开启GD库？
我们在实践过程中，白名单确实存活时间较久。
不过我们也发现，直接点击链接加入白名单直接暴露，墙的检测好像也可以加入白名单然后禁封ip。
目前我们的解决方案是重新写了加入白名单的add.php文件，打开链接后需要再次手动点击按钮加入白名单。
。。。。。。。。。持续测试中。
另外我们想加入个随机验证码功能，用户填写正确的验证码后，再点击手动加入白名单按钮可能更加有效的防止墙自动把它的ip加入系统。
但是该docker镜像中的php7.4没有开启gd库。如何开启gd库？

**Comment by ellermister** [comment]
apt install php7.4-gd

**Comment by timmyz** [comment]
> Docker镜像php7.4环境如何开启GD库？ 我们在实践过程中，白名单确实存活时间较久。 不过我们也发现，直接点击链接加入白名单直接暴露，墙的检测好像也可以加入白名单然后禁封ip。 目前我们的解决方案是重新写了加入白名单的add.php文件，打开链接后需要再次手动点击按钮加入白名单。 。。。。。。。。。持续测试中。 另外我们想加入个随机验证码功能，用户填写正确的验证码后，再点击手动加入白名单按钮可能更加有效的防止墙自动把它的ip加入系统。 但是该docker镜像中的php7.4没有开启gd库。如何开启gd库？

直接加个密码框，校验通过才能加白名单岂不更好？

**Comment by shipinbaoku** [comment]
> 

docker我不是很熟悉。是不是要进入docker容器内部安装GD组件？有没有详细的说明

**Comment by shipinbaoku** [comment]
`
docker ps
docker exec -it <容器id> /bin/bash
apt update
apt install php7.4-gd

`

已经安装成功，目前需要输入正确的验证码才可以加入白名单。看能生存多久！

**Comment by shipinbaoku** [comment]
如何不使用docker 使用白名单？

**Comment by yxbinghe-k** [comment]
> 如何不使用docker 使用白名单？

这是个好问题，同样想了解！

**Comment by yxbinghe-k** [comment]
> 如何不使用docker 使用白名单？

这是个好问题，同样想了解！

**Comment by yxbinghe-k** [comment]
还有，这两天脚本无法启动了！
大家是否遇到同样的问题？

**Comment by ellermister** [comment]
ip_white_list 可选参数为:

IP 允许单个 IP 访问
IPSEG 允许 IP 段访问
OFF 允许所有 IP 访问

https://hub.docker.com/r/ellermister/nginx-mtproxy

**Comment by yxbinghe-k** [comment]
> ip_white_list 可选参数为:
> 
> IP 允许单个 IP 访问 IPSEG 允许 IP 段访问 OFF 允许所有 IP 访问
> 
> https://hub.docker.com/r/ellermister/nginx-mtproxy

感谢你的回复！
我的意思是如何在非docker下部署，依然使用白名单功能！😄
谢谢，好运！
