### ISSUE TITLE
开启白名单就无法连接 （不知道是我的原因还是

### ISSUE THREAD

**Issue by Taylor000** [ellermister/mtproxy#21]
docker 安装，反反复复试了好几遍
在 ip_white_list="IP" 时，访问 http:ip/add.php 显示添加成功，docker logs 有显示，但还是不能使用， docker restart 尝试过；
在 ip_white_list="IPSEG" 时，http:ip/add.php 是直接打不开 503状态，代理不能使用；
只有 ip_white_list="OFF" 时才能链接，然后查看 docker logs 没有显示问题；
所以 这是我一个人的问题嘛 5555

**Comment by GuoliangLai** [comment]
一样有这个问题，所以直接就是不开启白名单了
