### ISSUE TITLE
The proxy you are using is notconfigured correctly and will bedisabled. Please find another one.

### ISSUE THREAD

**Issue by jwwsjlm** [ellermister/mtproxy#29]
![QQ截图20230309002720](https://user-images.githubusercontent.com/48446617/223773231-278f1abd-9079-48b0-95cb-62359c8f2595.png)
无法连接 这是vps的问题吗?

**Comment by ellermister** [comment]
使用 docker 进行配置基本不会出错。看不到你完整上下文，不确定你在做啥。

**Comment by jwwsjlm** [comment]
> 使用 docker 进行配置基本不会出错。看不到你完整上下文，不确定你在做啥。

就是使用一键脚本 过了两天又能正常链接了...不知道什么原因 刚刚配置好然后使用的话 就不行
