### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by GH6324** [ellermister/mtproxy#33]
1. Telegram 官方版本 (C语言, 存在一些问题, 只支持 x86_64)
2. 9seconds 第三方版本(兼容性强)
(默认版本: 1):2

安装脚本直接停止：
Installed for mtg
./mtg run ee88a7d5b98e728e51312db665f15f1265617a7572652e6d6963726f736f66742e636f6d -b 0.0.0.0:4445 --multiplex-per-connection 500 --prefer-ip=ipv6 -t 127.0.0.1:4446
TMProxy+TLS代理: 已停止

直接运行命令报错如下：
root@myhost:/home/mtproxy# ./mtg run ee88a7d5b98e728e51312db665f15f1265617a7572652e6d6963726f736f66742e636f6d -b 0.0.0.0:4445 --multiplex-per-connection 500 --prefer-ip=ipv6 -t 127.0.0.1:4446
fatal error: cannot resolve any public address

**机器是AWS的Lightsail，系统为Debian11，网络环境为仅ipv4，已关闭ipv6，系统DNS为8.8.8.8**

**Comment by ellermister** [comment]
还有这个问题吗

**Comment by GH6324** [comment]
> 还有这个问题吗

刚刚试了一下还是这个问题。。不确定是系统问题还是网络问题。。

**Comment by rebecca554owen** [comment]
lightsail机器会遇到这个问题，fatal error: cannot resolve any public address，选1用官方版本即可。

**Comment by ellermister** [comment]
已经更新
