### ISSUE TITLE
MTProxy Secret信息和链接生成的不一样

### ISSUE THREAD

**Issue by ixmu** [ellermister/mtproxy#9]
生成链接Secret位数很多，而telegram bot要求：
Incorrect secret value. It must contain 32 hex characters like 
00112233445566778899aabbccddeeff.

**Comment by ellermister** [comment]
这里可以随便填，你直接复制 BOT 给你吐的 00112233445566778899aabbccddeeff 也可以用的。
这里不做校验，最终分享使用的链接不要通过 BOT 反馈给你的，直接复制脚本生成的就能用。
